### ISSUE TITLE
No fixes recognized for repository

### ISSUE THREAD

**Issue by miguelnietoa** [step-security/secure-repo#1720]
The repo https://github.com/kommitters/elixir_xdr contains CI and CD GitHub actions that have no pinned dependencies. However, the tool does not recognize them... 🤔 

CI: https://github.com/kommitters/elixir_xdr/blob/e74f71cc5919695bcabcebe612ed8324699ad0c1/.github/workflows/CI.yml
CD: https://github.com/kommitters/elixir_xdr/blob/e74f71cc5919695bcabcebe612ed8324699ad0c1/.github/workflows/CD.yml

![image](https://user-images.githubusercontent.com/39246879/209190655-cc6a0997-d71a-43cc-8f36-b9c822959124.png)

**Comment by miguelnietoa** [comment]
I noticed that it is because of the filenames. 

In my fork (https://github.com/miguelnietoa/elixir_xdr), I renamed the files to `ci.yml` and `cd.yml` and now it works.

![image](https://user-images.githubusercontent.com/39246879/209369208-190524ca-d889-4c60-8fb7-3e55e5772fe4.png)

**Comment by miguelnietoa** [comment]
Hey, @varunsh-coder any idea why it happens?

**Comment by varunsh-coder** [comment]
Sorry @miguelnietoa looks like I missed the original issue. I will investigate and get back. I am re-opening the issue since it seems valid.

**Comment by varunsh-coder** [comment]
@h0x0er, can you please investigate this? It might have to do with case sensitivity.

**Comment by varunsh-coder** [comment]
This was fixed a while back, so closing issue. Feel free to re-open if you see the issue again. Thanks!

**Comment by miguelnietoa** [comment]
Thank you @varunsh-coder 💯
