### ISSUE TITLE
Docker fix fails when tag not specified for image

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/secure-repo#1932]
https://github.com/step-security/secure-repo/blob/77dcaa8f04139643d06fba8f5a031450a1970832/remediation/workflow/pin/pindocker.go#L45 assumes that a tag is always specified. When it is not specified, the code fails. 

Here is an example
https://github.com/onnx/onnx/blob/540c58b4fa622c99880bcd2ea086089cae56bc9d/.github/workflows/release_linux_x86_64.yml#L46

- [ ] We need to figure out how to fix an issue when the tag is not specified. 
- [ ] Handle cases when the tag is not specified and not error out

**Comment by zwass** [comment]
Same issue here: https://github.com/fleetdm/fleet/pull/10205

Files it missed:
- https://github.com/fleetdm/fleet/blob/main/Dockerfile
- https://github.com/fleetdm/fleet/blob/main/Dockerfile-desktop-linux (maybe not different issue?)
- https://github.com/fleetdm/fleet/blob/main/Dockerfile.osquery-perf (maybe different issue?)

**Comment by varunsh-coder** [comment]
Thanks, @zwass, for updating the issue and trying this out!

I have added a couple of related issues based on your PR. 
https://github.com/step-security/secure-repo/issues/1955
https://github.com/step-security/secure-repo/issues/1954

**Comment by varunsh-coder** [comment]
This issue is fixed in v1.3.1 and released. #1954 is also fixed.
