### ISSUE TITLE
Docker image is pinned when already pinned

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/secure-repo#1954]
See this example:
https://github.com/fleetdm/fleet/pull/10205/files/0d98d9f31120b05f57d757d6ac96bce5632bd6d9..5ce95d8bf8496f39eac930a9d90c2e8af27b3caf

We need to check if the image is already pinned, then, it should not be pinned again.

**Comment by varunsh-coder** [comment]
@Devils-Knight can you please take this up? Do add a test case for this scenario.

**Comment by Devils-Knight** [comment]
@varunsh-coder I think there is already code in place for this scenario, view [here](https://github.com/step-security/secure-repo/blob/77dcaa8f04139643d06fba8f5a031450a1970832/remediation/docker/securedockerfile.go#L55).
The file above mentioned has pinned the image twice so it just removed one of the hash.

**Comment by varunsh-coder** [comment]
This is released. Good work @Devils-Knight!
