### ISSUE TITLE
Retain docker image tag when pinning in Actions workflows

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/secure-repo#1999]
@Devils-Knight I noticed that when we pin docker images in Github Actions workflows, we do not retain the tag. 

On the other hand, when we pin docker images in dockerfiles, we do retain the tag. Here is an example:
https://github.com/step-security/secure-repo/blob/abc34e314c750e5463d0b3e06893d90eb5abb99a/testfiles/dockerfiles/output/Dockerfile-not-pinned-as#L16

The `3.7` tag part is retained. 

As next steps:
1. Can you please investigate that if the tag is retained for docker images in GitHub Actions workflows, does it work fine, and does dependabot update it?
2. If yes, make changes to retain the tag in GitHub Actions workflows. 

In this case, the test cases would also need to be updated.

**Comment by Devils-Knight** [comment]
I think we can retain tag for docker image in the given format that you mentioned and the retained tag would act as a fallback option in case referencing the pinned tag version fails, view [here](https://github.com/whilp/world/actions/runs/3854539457/jobs/6568636092#step:2:1).

And for the dependabot part, The functionality for bumping docker actions isn't added yet. There is an open issue tracking this functionality. [dependabot/dependabot-core/issues/5541](https://github.com/dependabot/dependabot-core/issues/5541)

I have created a pr updating the format and test cases for the same. 
[Update Format for Pinning Docker Actions #2014
](https://github.com/step-security/secure-repo/pull/2014)

**Comment by varunsh-coder** [comment]
This is done and released. Thanks!
