### ISSUE TITLE
Replace tag if already exists when pinning Action

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/secure-repo#2064]
See this case: 
https://github.com/deislabs/ratify/pull/755#pullrequestreview-1373868550

**Comment by varunsh-coder** [comment]
@arjundashrath please take this up

**Comment by arjundashrath** [comment]
@varunsh-coder looks like we append to the actions line and keep the previous comments. So should I delete all previous comments or should I add logic looking for a tag and removing if it matches? in that case, what all keywords should I look for?

**Comment by varunsh-coder** [comment]
I believe we can remove any previous comments since they come after an action tag and are meant for updating purposes. Please include a test case using the workflow file that experienced this problem.

**Comment by varunsh-coder** [comment]
this is fixed and released. good work @arjundashrath!
