### ISSUE TITLE
Dashboard Access Request

### ISSUE THREAD

**Issue by UlisesGascon** [step-security/secure-repo#2094]
I will love to the test [the new dashboard](https://www.linkedin.com/posts/varunsharma07_introducing-the-game-changing-org-wide-activity-7053857320144941056-rXVX) with two organizations ([onebeyond](https://github.com/onebeyond) and [Guidesmiths](https://github.com/guidesmiths)) and I will provide you feedback after few days of usage with my colleagues 🙌.

**Comment by varunsh-coder** [comment]
@UlisesGascon I will go ahead and close this issue.
