### ISSUE TITLE
An issue with yaml format on dependantbot.yml generated

### ISSUE THREAD

**Issue by fperezel** [step-security/secure-repo#2139]
Hi,

A dependantbot.yml generated in PR https://github.com/eclipse-platform/eclipse.platform.ui/pull/764 for repo https://github.com/eclipse-platform/eclipse.platform.ui is not a valid yaml.

You have more information in this link below, https://github.com/eclipse-platform/eclipse.platform.ui/issues/761#issuecomment-1551859847

Thanks,

Kind Regards,

**Comment by fperezel** [comment]
Hi,

We have found out this issue in 7 out of 11 PR generated. Unfortunately, no pattern and root cause hasn't found yet.

Please find below a table which summaries the analysis done so far.

link | Comment
-- | --
https://github.com/eclipse-platform/eclipse.platform/pull/457 | Issue generating dependabot.yml -> https://github.com/eclipse-platform/eclipse.platform/pull/457/commits/c4dcda915715eb435decb4045fc3e3d7831378ee
https://github.com/eclipse-platform/eclipse.platform.debug/pull/146 | Issue generating dependabot.yml -> https://github.com/step-security-bot/eclipse.platform.debug/blob/065236d508bc4e1efa90bdc5a7f1634a66921ff2/.github/dependabot.yml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1069 | Issue generating dependabot.yml -> https://github.com/step-security-bot/eclipse.platform.ui/blob/093b09210a0ac02f04624424f85c42f536767ec5/.github/dependabot.yml
https://github.com/eclipse-platform/eclipse.platform.ui/pull/762 | Issue generating dependabot.yml -> https://raw.githubusercontent.com/step-security-bot/eclipse.platform.ui/093b09210a0ac02f04624424f85c42f536767ec5/.github/dependabot.yml
https://github.com/eclipse-platform/eclipse.platform.ui/issues/761 | Issue generating dependabot.yml -> https://github.com/step-security-bot/eclipse.platform.ui/blob/093b09210a0ac02f04624424f85c42f536767ec5/.github/dependabot.yml
https://github.com/eclipse-platform/eclipse.platform.ua/pull/133 | Issue generating dependabot.yml -> https://raw.githubusercontent.com/step-security-bot/eclipse.platform.ua/2788c418941ab0d76bf4aead8201cd942d0ebe70/.github/dependabot.yml
https://github.com/eclipse-platform/ui-best-practices/pull/71 | No Issues generating, https://github.com/step-security-bot/ui-best-practices/blob/fd42cfa2fd4b039e271f1b587af51e07be32d8d4/.github/dependabot.yml
https://github.com/eclipse-platform/eclipse.platform.swt.binaries/pull/42 | No issues generating, https://raw.githubusercontent.com/step-security-bot/eclipse.platform.swt.binaries/6e7fd7ccfd691c983e40227ca8348ffef2084844/.github/dependabot.yml
https://github.com/eclipse-platform/eclipse.platform.text/pull/202 | Issue generatin dependabot.yml -> https://raw.githubusercontent.com/step-security-bot/eclipse.platform.text/5ca31eabb40fcd3b084b2f709cb59576e048a091/.github/dependabot.yml
https://github.com/eclipse-platform/www.eclipse.org-eclipse-news/pull/104 | No issue generating a dependabot.yaml from scratch -> https://raw.githubusercontent.com/step-security-bot/www.eclipse.org-eclipse-news/fbdf09958d269ed08133f86a58f30e5dfa817a5b/.github/dependabot.yml



Kind Regards,

**Comment by varunsh-coder** [comment]
Thanks for reporting @fperezel! Based on my analysis, Dependabot allows for adding `package-ecosystem` without indentation as well. The code in this repo assumes that the `package-ecosystem` has to be added with indentation, and so does that without looking at the current indentation, which causes the bug. 

The code needs to first detect the indentation and then apply the changes based on the current indentation. We will work on a fix for it ASAP.

**Comment by varunsh-coder** [comment]
Hi @fperezel this issue is now fixed and released. 

Here is an example where I reproduced the issue where dependabot.yml has no indentation for the list
https://github.com/varunsh-coder/test/pull/20/files

This is the same scenario which was giving an issue before the fix. 

Please test it out on your end and let me know if you see any issues.

**Comment by fperezel** [comment]
Thanks for the feed back, then I am closing this ticket.
