### ISSUE TITLE
Permissions required by token option in trufflehog github command 

### ISSUE THREAD

**Issue by MukulG27** [step-security/secure-repo#2226]
I am running trufflehog using docker in a jenkins pipeline
I need to scan repositories of a private organisation and for that I use the command
`docker run --rm -v pwd:/pwd trufflesecurity/trufflehog:latest trufflehog github --repo <repo-name> --token <token>`
What permissions are required by the token

**Comment by varunsh-coder** [comment]
Hi @MukulG27 I am not sure of the permissions needed in your scenario. You could ask this question in the https://github.com/trufflesecurity/trufflehog repository.
